-- Migration Script: Import old products into products_new table

INSERT INTO `products_new` (
    `id`, 
    `slug`, 
    `name`, 
    `meta_title`, 
    `meta_description`, 
    `hero_heading`, 
    `hero_subheading`, 
    `hero_description`, 
    `hero_button_text`, 
    `hero_button_link`, 
    `hero_image`, 
    `why_heading`, 
    `why_description`, 
    `why_button_text`, 
    `why_button_link`, 
    `summary_heading`, 
    `modules_heading`, 
    `features_heading`, 
    `features_subheading`, 
    `audiences_heading`, 
    `industries_heading`, 
    `technology_heading`, 
    `pricing_heading`, 
    `pricing_subheading`, 
    `faq_heading`, 
    `demo_call_to_action_heading`, 
    `demo_call_to_action_button_text`, 
    `demo_call_to_action_button_link`, 
    `created_at`
) VALUES 
(1, 'sheba-erp', 'Sheba ERP | Best ERP Software in Bangladesh', 'Sheba ERP | Best ERP Software in Bangladesh', 'SHEBA ERP System of Mysoft Heaven BD Ltd is the best ERP system in Dhaka for maintaining your total organization tasks.', 'Sheba ERP System', 'Best ERP Software in Bangladesh', 'SHEBA ERP System of Mysoft Heaven BD Ltd is the best ERP system in Dhaka for maintaining your total organization tasks and a complete Enterprise Resource Planning System.', 'Get Started', 'http://173.212.223.213/erp', 'Sheba_ERP.png', 'Why Sheba ERP?', 'If you are want to access your data smoothly then \'Sheba\' ERP Software is the best choice. With this software, you can combine an enormous quantity of data into a single file/system. Consequently, in this way to develop the effectiveness of an organization.', 'Contact Us', 'contact-us', 'System Summary', 'Our Modules', 'Key Features', 'Explore the powerful features that manage your organization.', 'Who can use this?', 'Industries We Serve', 'Technology Stack', 'Pricing Plans', 'Choose the plan that fits your organization.', 'Frequently Asked Questions', 'Ready to Optimize Your Business?', 'Request Demo', 'http://173.212.223.213/erp', NOW()),

(2, 'best-hr-software-in-bangladesh', 'HR Sheba | Best HR Software in Bangladesh', 'HR Sheba | Best HR Software in Bangladesh', 'Looking for the Best HR Software in Bangladesh to simplify and automate your human resources operations?', 'HR Sheba', 'Complete HRM, Payroll & Attendance', 'Our all-in-one HR management platform is built to streamline every step of the employee lifecycle—from hiring to retirement—while ensuring full compliance with local labor laws.', 'Get Started', 'http://173.212.223.213/hrsheba', '438231103_374761272223436_6091012394832469885_n.jpg', 'Why HR Sheba?', 'Covers complete employee lifecycle, Supports both compliant and non-compliant payroll, Built with factory and corporate HR needs in mind, highly customizable and dynamic.', 'Contact Us', 'contact-us', 'System Summary', 'Core Modules', 'Key Features', 'Everything you need to manage your workforce.', 'Target Audience', 'Industries We Serve', 'Technology Stack', 'Pricing Plans', 'Flexible plans for your team size.', 'Frequently Asked Questions', 'Ready to Streamline HR?', 'Request Demo', 'http://173.212.223.213/hrsheba', NOW()),

(3, 'salesman', 'Salesman | Point of Sales', 'Salesman | Point of Sales', 'Point of sales is the zone of bill payment by the customer to salesman and Salesman app is here to minimize the harassments of the billing system.', 'Salesman POS', 'Efficient Point of Sales System', 'Point of sales is the zone of bill payment by the customer to salesman and Salesman app is here to minimize the harassments of the billing system.', 'Get Started', 'http://173.212.223.213/Salesman', 'WhatsApp_Image_2024-10-30_at_12_28_19_PM.jpeg', 'Why Salesman POS?', 'To calculate the amount owed by a customer, the employee may use various devices such as weighing scales, barcode scanners, and cash registers. To make a payment, payment terminals, touch screens, other hardware and software options are available.', 'Contact Us', 'contact-us', 'System Statistics', 'POS Modules', 'Features', 'Fast and reliable billing features.', 'Who uses Salesman?', 'Industries', 'Technology Stack', 'Pricing Plans', 'Affordable POS solutions.', 'FAQ', 'Ready to speed up sales?', 'Request Demo', 'http://173.212.223.213/Salesman', NOW()),

(4, 'binyog', 'Binyog | Leading Investment Management Software', 'Binyog | Leading Investment Management Software', 'Biniyog is the complete Multipurpose Management system to secure your investment return.', 'Binyog Software', 'Leading Investment Management', 'Biniyog is the complete Multipurpose Management system to secure your investment return. This Multipurpose management system control your investment system to get the best return.', 'Get Started', 'http://173.212.223.213/Multi Purpose', 'Binyog.png', 'Why Binyog?', 'Biniyog is the leading investment management software gives you real-time investment management analytics and data to help improve decision making.', 'Contact Us', 'contact-us', 'Summary', 'Modules', 'Features', 'Manage your investments smartly.', 'Audience', 'Industries', 'Technology Stack', 'Pricing Plans', 'Investment plans.', 'FAQ', 'Secure your returns today', 'Request Demo', 'http://173.212.223.213/Multi Purpose', NOW()),

(5, 'filling-master', 'Filling Master (ফিলিং মাস্টার)', 'Filling Master (ফিলিং মাস্টার)', 'A petrol pump management software is actually designed for a petroleum pump owner or Associate in nursing enterpriser running a petroleum pump business.', 'Filling Master', 'Petrol Pump Management System', 'A petrol pump management software is actually designed for a petroleum pump owner or Associate in nursing enterpriser running a petroleum pump business. The computer code can even be effectively employed by a petroleum pump chain.', 'Get Started', 'http://173.212.223.213/point_of_sale/index.php/main/generate_token', 'Filling_Master.png', 'Why Filling Master?', 'Calculate meter readings, density, credit system, inventory management, VAT integration, shift wise report, and more.', 'Contact Us', 'contact-us', 'Summary', 'Modules', 'Features', 'Control fuel theft and billing errors.', 'Audience', 'Industries', 'Technology Stack', 'Pricing Plans', 'Plans for pump owners.', 'FAQ', 'Optimize your pump station', 'Request Demo', 'http://173.212.223.213/point_of_sale/index.php/main/generate_token', NOW()),

(6, 'smart-educare', 'SMART Educare | Education management system', 'SMART Educare | Education management system', 'Smart Educare is a complete Educational Institute Management system Software in Bangladesh to keep records and maintain the system in a smart way.', 'SMART Educare', 'Education Management System', 'Smart Educare is a complete Educational Institute Management system Software in Bangladesh by Mysoftheaven BD Ltd to use in Govt educational project to keep records and maintain the system in a smart way.', 'Get Started', 'http://173.212.223.213/school/demo/', 'SMART_Educare.png', 'Why Smart Educare?', 'Manage student attendance, results, fees, transport, and more with a complete school management ERP.', 'Contact Us', 'contact-us', 'Summary', 'Modules', 'Features', 'Streamline your educational institution.', 'Audience', 'Industries', 'Technology Stack', 'Pricing Plans', 'School management packages.', 'FAQ', 'Transform your school', 'Request Demo', 'http://173.212.223.213/school/demo/', NOW()),

(7, 'gym-master', 'Gym Master (জিম মাস্টার)', 'Gym Master (জিম মাস্টার)', 'Gym Master is gym management software designed to easily maintain of detailed records of your members, different packages, trainers, process and track sales.', 'Gym Master', 'Gym Management Software', 'Gym Master is gym management software designed to easily maintain of detailed records of your members, different packages, trainers, process and track sales, communicate with the right members at the right time and growth of your club.', 'Get Started', 'http://173.212.223.213/', 'Gym_Master.png', 'Why Gym Master?', 'Member tracking, package management, payment processing, product management, and reporting analysis.', 'Contact Us', 'contact-us', 'Summary', 'Modules', 'Features', 'Manage your gym efficiently.', 'Audience', 'Industries', 'Technology Stack', 'Pricing Plans', 'Gym packages.', 'FAQ', 'Grow your fitness club', 'Request Demo', 'http://173.212.223.213/', NOW()),

(8, 'sompod', 'Sompod - (সম্পদ) | Best Store Management system', 'Sompod - (সম্পদ) | Best Store Management system', 'Sompod | A complete Inventory/Best Store Management system for managing your inventory product and also things of your store.', 'Sompod', 'Best Store Management System', 'Sompod | A complete Inventory/Best Store Management system for managing your inventory product and also things of your store brought by Mysoftheaven BD Ltd.', 'Get Started', 'http://173.212.223.213/inventory_management/login/generate_token', 'Sompod.png', 'Why Sompod?', 'Track inventory levels, orders, sales, and deliveries. Manage stock, audits, warehouses, expirations, and billing integration.', 'Contact Us', 'contact-us', 'Summary', 'Modules', 'Features', 'Optimize your inventory.', 'Audience', 'Industries', 'Technology Stack', 'Pricing Plans', 'Inventory plans.', 'FAQ', 'Manage your store better', 'Request Demo', 'http://173.212.223.213/inventory_management/login/generate_token', NOW()),

(9, 'hr-master', 'HR Master (এইচআর মাস্টার) | HR Management system', 'HR Master (এইচআর মাস্টার)', 'HR Master is the complete HR Management system for employee management and consultancy in Bangladesh by Mysoftheaven BD Ltd.', 'HR Master', 'HR Management System', 'HR Master is the complete HR Management system for employee management and consultancy in Bangladesh by Mysoftheaven BD Ltd.', 'Get Started', 'http://173.212.223.213/', 'HR_Master.png', 'Why HR Master?', 'Improve HR department efficiency, enhance internal communication, minimize business costs, monitor employee data, and help decision making.', 'Contact Us', 'contact-us', 'Summary', 'Modules', 'Features', 'Complete HR Solution.', 'Audience', 'Industries', 'Technology Stack', 'Pricing Plans', 'HR Plans.', 'FAQ', 'Streamline HR processes', 'Request Demo', 'http://173.212.223.213/', NOW()),

(10, 'crm', 'SMART CRM | Best CRM Tool', 'SMART CRM | Best CRM Tool', 'Customer Relationship Management (CRM) is a technology to analyze an organization’s relationships and interactions with potential customers.', 'SMART CRM', 'Best CRM Tool', 'Customer Relationship Management (CRM) is a technology to analyze an organization’s relationships and interactions with potential customers. Mysoftheaven builds the best CRM software in the market.', 'Get Started', 'http://173.212.223.213/', 'Smart_CRM.png', 'Why SMART CRM?', 'Contact management, lead generation, sales forecasting, customer support management, inventory management, and accounts management.', 'Contact Us', 'contact-us', 'Summary', 'Modules', 'Features', 'Boost your sales and relations.', 'Audience', 'Industries', 'Technology Stack', 'Pricing Plans', 'CRM Packages.', 'FAQ', 'Grow your customer base', 'Request Demo', 'http://173.212.223.213/', NOW());

